# Generated by Django 5.0.6 on 2024-07-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_remove_book_status_alter_book_id_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
